/**
 * Web Service Build System
 */

const gulp = require('gulp');
const pump = require('pump');
const fs = require('fs');
const del = require('del');
const rename = require('gulp-rename');
const replace = require('gulp-replace');
const markdown = require('gulp-markdown');

/**
 * Converts Markdown help into the HTML format
 */
gulp.task('parse-doc', function (cb) {
  pump(
    gulp.src('doc/asset/help.md', {base: './'}),
    markdown(),
    gulp.dest('.'),
    cb
  )
});

/**
 * Wraps the help content in the HTML container
 */
gulp.task('build-doc', function (cb) {
  pump(
    gulp.src('doc/asset/container.html', {base: './'}),
    replace('{{api}}', () => {
      return fs.readFileSync('doc/asset/help.html');
    }),
    replace(' id="-"', ''), // remove extra element IDs generated by marked
    rename('doc/index.html'),
    gulp.dest('.'),
    cb
  )
});

/**
 * Removes extra files
 */
gulp.task('cleanup', function (cb) {
  del(['doc/asset/help.html']);
  cb();
});

/**
 * Executes all tasks one after the other
 */
gulp.task('default', gulp.series('parse-doc', 'build-doc', 'cleanup'));

/**
 * Builds on changes in files
 */
gulp.task('watch', () => {
  gulp.watch(['samples/**', 'doc/**'], gulp.series('default'));
});
